#!/usr/bin/python3
'''
Def: Class storage
'''
import json
from models.base_model import BaseModel
from models.user import User
from models.state import State
from models.city import City
from models.amenity import Amenity
from models.place import Place
from models.review import Review


class FileStorage():
    '''Representing file Storage.
    '''
    __file_path = "file.json"
    __objects = {}

    def all(self):
        '''Retreive all class instances objects
        '''
        return FileStorage.__objects

    def new(self, obj):
        '''Creating a new Object
        '''
        FileStorage.__objects["{}.{}".format(
            obj.__class__.__name__, obj.id)] = obj

    def save(self):
        '''def save
        '''
        with open(FileStorage.__file_path, "w") as f:
            obj = {}
            for k, v in FileStorage.__objects.items():
                obj[k] = v.to_dict()
            string = json.dumps(obj)
            f.write(string)

    def reload(self):
        '''Reload data
        '''
        try:
            with open(FileStorage.__file_path, "r") as f:
                data = json.load(f)
                for k, v in data.items():
                    print("ok")
                    cl_name = eval(k["__class__"])
                    self.new((cl_name)(**v))
        except Exception:
            pass
